version: '3.5'

services:
  postgres:
    container_name: postgres_db
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ${POSTGRES_DB:-northwind}
      DB_ANON_ROLE: ${DB_ANON_ROLE}
      DB_SCHEMA: ${DB_SCHEMA}
      PGDATA: /data/postgres
    volumes:
       #- ./databases/entrypoint.sh:/docker-entrypoint-initdb.d/init.sh
       - ./databases/:/docker-entrypoint-initdb.d/
    ports:
      - "65432:5432"
    networks:
      - postgres
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin:
